name: Penugasan 1 NETICS

on:
  push:
    branches:
      - main

jobs:
  # Build docker
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: adieos
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t adieos/netics-1:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push adieos/netics-1:latest

  # Pull image, deploy with docker compose
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/penugasan-1-netics
            sudo docker pull adieos/netics-1:latest
            sudo docker-compose down 
            sudo docker-compose up -d